

--测试数据 AUTO_INCREMENT
create table user(
  id INT not null ,
  name VARCHAR(20),
  age INT,
  PRIMARY key(id)
);

create table T_ACTOR(
  id INT PRIMARY key GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  first_name VARCHAR(20),
  last_name VARCHAR(20),
  age INT,
  specialty VARCHAR (20)
);